// Generated by https://quicktype.io

export interface User {
  id:       string;
  name:     string;
  lastname: string;
  username: string;
  role:     string;
}

export interface TableUsers {
  users: User[] | null
}
